# This file contains values from Cookiecutter

default_context:
  project_name: "fusionpbx-pilot"
  project_description: "FusionPBX Pilot is a Python package to manage FusionPBX interface as a python library."
  organization: "Gnovit"
  license: "GNU GPL v3.0"
  minimal_python_version: 3.9
  github_name: "gnovit"
  email: "marcelo@gnovit.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
